# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-19 20:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DB_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_name', models.CharField(max_length=100, unique=True)),
                ('db_type', models.CharField(choices=[('psql', 'PostgreSQL'), ('mysql', 'MySQL'), ('mongo', 'MongoDB')], max_length=25)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=500)),
                ('password', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('port', models.IntegerField(default=0)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
