# Generated by Django 2.1 on 2018-12-17 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_name', models.CharField(max_length=100, unique=True)),
                ('table_name', models.CharField(max_length=100, unique=True)),
                ('column_name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('database_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='db_details', to='backend.DB_details')),
            ],
        ),
    ]
