# Generated by Django 2.1 on 2018-12-18 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20181218_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charts',
            name='slug',
            field=models.SlugField(),
        ),
    ]
